version: "3"

services:

  postgres:
    image: postgres:15.1
    container_name: Magazin_db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    restart: unless-stopped
    volumes:
      - ./datadase-magazin:/var/lib/postgesql/data
    ports:
      - "5432:5432"

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./media:/opt/app/media
    ports:
      - "80:80"

